// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: v1/agent.proto

package verterapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task types the controller can assign to agents
type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED      TaskType = 0
	TaskType_TASK_TYPE_INSTALL_PACKAGES TaskType = 1
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_INSTALL_PACKAGES",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED":      0,
		"TASK_TYPE_INSTALL_PACKAGES": 1,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_agent_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_v1_agent_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{0}
}

type InstallPackagesParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      []string               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`                    // e.g., ["ovs", "cloud-hypervisor"]
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                      // optional
	OsVersion     string                 `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"` // optional (e.g., "el9")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackagesParams) Reset() {
	*x = InstallPackagesParams{}
	mi := &file_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackagesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackagesParams) ProtoMessage() {}

func (x *InstallPackagesParams) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackagesParams.ProtoReflect.Descriptor instead.
func (*InstallPackagesParams) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *InstallPackagesParams) GetPackages() []string {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *InstallPackagesParams) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallPackagesParams) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HostId        string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Type          TaskType               `protobuf:"varint,3,opt,name=type,proto3,enum=vertera.v1.TaskType" json:"type,omitempty"`
	Params        []byte                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"` // Marshaled InstallPackagesParams for now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Task) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type TaskAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAck) Reset() {
	*x = TaskAck{}
	mi := &file_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAck) ProtoMessage() {}

func (x *TaskAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAck.ProtoReflect.Descriptor instead.
func (*TaskAck) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TaskAck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // queued, running, succeeded, failed
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`   // non-empty when failed
	Logs          string                 `protobuf:"bytes,4,opt,name=logs,proto3" json:"logs,omitempty"`     // optional inline logs snippet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *TaskResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignedId    string                 `protobuf:"bytes,1,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

var File_v1_agent_proto protoreflect.FileDescriptor

const file_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/agent.proto\x12\n" +
	"vertera.v1\"l\n" +
	"\x15InstallPackagesParams\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\tR\bpackages\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tR\tosVersion\"q\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.vertera.v1.TaskTypeR\x04type\x12\x16\n" +
	"\x06params\x18\x04 \x01(\fR\x06params\"\x19\n" +
	"\aTaskAck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\n" +
	"TaskResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04logs\x18\x04 \x01(\tR\x04logs\"H\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"3\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vassigned_id\x18\x01 \x01(\tR\n" +
	"assignedId*E\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTASK_TYPE_INSTALL_PACKAGES\x10\x012\xd5\x01\n" +
	"\fAgentService\x12E\n" +
	"\bRegister\x12\x1b.vertera.v1.RegisterRequest\x1a\x1c.vertera.v1.RegisterResponse\x12=\n" +
	"\n" +
	"WatchTasks\x12\x1b.vertera.v1.RegisterRequest\x1a\x10.vertera.v1.Task0\x01\x12?\n" +
	"\x10ReportTaskResult\x12\x16.vertera.v1.TaskResult\x1a\x13.vertera.v1.TaskAckB5Z3github.com/VerteraIO/vertera/api/proto/v1;verterapbb\x06proto3"

var (
	file_v1_agent_proto_rawDescOnce sync.Once
	file_v1_agent_proto_rawDescData []byte
)

func file_v1_agent_proto_rawDescGZIP() []byte {
	file_v1_agent_proto_rawDescOnce.Do(func() {
		file_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)))
	})
	return file_v1_agent_proto_rawDescData
}

var file_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_agent_proto_goTypes = []any{
	(TaskType)(0),                 // 0: vertera.v1.TaskType
	(*InstallPackagesParams)(nil), // 1: vertera.v1.InstallPackagesParams
	(*Task)(nil),                  // 2: vertera.v1.Task
	(*TaskAck)(nil),               // 3: vertera.v1.TaskAck
	(*TaskResult)(nil),            // 4: vertera.v1.TaskResult
	(*RegisterRequest)(nil),       // 5: vertera.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 6: vertera.v1.RegisterResponse
}
var file_v1_agent_proto_depIdxs = []int32{
	0, // 0: vertera.v1.Task.type:type_name -> vertera.v1.TaskType
	5, // 1: vertera.v1.AgentService.Register:input_type -> vertera.v1.RegisterRequest
	5, // 2: vertera.v1.AgentService.WatchTasks:input_type -> vertera.v1.RegisterRequest
	4, // 3: vertera.v1.AgentService.ReportTaskResult:input_type -> vertera.v1.TaskResult
	6, // 4: vertera.v1.AgentService.Register:output_type -> vertera.v1.RegisterResponse
	2, // 5: vertera.v1.AgentService.WatchTasks:output_type -> vertera.v1.Task
	3, // 6: vertera.v1.AgentService.ReportTaskResult:output_type -> vertera.v1.TaskAck
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_agent_proto_init() }
func file_v1_agent_proto_init() {
	if File_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_agent_proto_rawDesc), len(file_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_agent_proto_goTypes,
		DependencyIndexes: file_v1_agent_proto_depIdxs,
		EnumInfos:         file_v1_agent_proto_enumTypes,
		MessageInfos:      file_v1_agent_proto_msgTypes,
	}.Build()
	File_v1_agent_proto = out.File
	file_v1_agent_proto_goTypes = nil
	file_v1_agent_proto_depIdxs = nil
}
